name = "ModelTesting"
uuid = "726cd793-0c59-4a7a-97d2-1baad301d093"
authors = ["Ben Chung <benjamin.chung@juliahub.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
